#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DYNAMIC_MACRO_NO_NESTING 1

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD 1

#define VIM_FOR_ALL 1
#define VIM_FOR_MAC 1
#define BETTER_VISUAL_MODE 1
#define VIM_G_MOTIONS 1
#define VIM_COLON_CMDS 1
#define VIM_PASTE_BEFORE 1
#define VIM_REPLACE 1
#define VIM_DOT_REPEAT 1
// #define VIM_W_BEGINNING_OF_WORD 1
// #define VIM_NUMBERED_JUMPS 1