MCU = RP2040
BOOTLOADER = rp2040
VIA_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes

CAPS_WORD_ENABLE = yes

OS_DETECTION_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes

TAP_DANCE_ENABLE = yes

RGBLIGHT_ENABLE = yes
# RGBLIGHT_LAYERS_ENABLE = yes
# DEFERRED_EXECUTOR_ENABLE = yes

# Debugging
# CONSOLE_ENABLE = yes